---
title: "3. Prepare METABRIC data"
output: html_notebook
---

## Initial setup

### Load library
```{r}
library(dplyr)
```

### Set paths
```{r}
metabric_dir <- "~/Dropbox (HMS)/_projects_/B06 03 HR-APM/data/metabric"
obj_dir <- "~/Dropbox (HMS)/_projects_/B06 03 HR-APM/data/RData"
```

### Gene list
```{r}
load(file=file.path(obj_dir,"gene_list.rda")) # gene.sig,category,hallmarks
```

## Load expresssion data (downloaded form cBioPortal)
```{r}
## expression matrix
fns <-   file.path(metabric_dir,
                   c("data_expression_median.txt",
                  	 "data_mRNA_median_Zscores.txt",
                     "data_mRNA_median_all_sample_Zscores.txt"))

meta.mat1 <- read.table(fns[1],sep="\t",header=T,stringsAsFactors=F)
meta.mat2 <- read.table(fns[2],sep="\t",header=T,stringsAsFactors=F)
meta.mat3 <- read.table(fns[3],sep="\t",header=T,stringsAsFactors=F)

meta.mat1[1:5,1:5]
```
### Check column names
Column names of the three matrices are identical.
```{r}
identical(colnames(meta.mat1),colnames(meta.mat2)) # true
identical(colnames(meta.mat1),colnames(meta.mat3)) # true
```

## Pre-processing data
### Compare three expression matrices
```{r}
## colnames - identical
meta.m1 <- as.matrix(meta.mat1[,-(1:2)])
meta.m2 <- as.matrix(meta.mat2[,-(1:2)])
meta.m3 <- as.matrix(meta.mat3[,-(1:2)])

dim(meta.m1) # 24368 genes, 1904 samples
dim(meta.m2) # 18543 genes, 1904 samples
dim(meta.m3) # 24368 genes, 1904 samples
```

### mat1 and mat3 have identical gene sets.
```{r}
identical(meta.mat1$Hugo_Symbol,meta.mat3$Hugo_Symbol) # true
```

### colnames are unique
```{r}
table(table(colnames(meta.m3)))
```


```{r}
syms12 <- intersect(meta.mat1$Hugo_Symbol,meta.mat2$Hugo_Symbol)

i=4
plot(meta.m1[match(syms12[i],meta.mat1$Hugo_Symbol),],
	meta.m2[match(syms12[i],meta.mat2$Hugo_Symbol),],
	main=syms12[i],
	xlab="M1",ylab="M2",	
	pch=20)
plot(meta.m1[match(syms12[i],meta.mat1$Hugo_Symbol),],
	meta.m3[match(syms12[i],meta.mat3$Hugo_Symbol),],
	main=syms12[i],
	xlab="M1",ylab="M3",
	pch=20)
plot(meta.m2[match(syms12[i],meta.mat2$Hugo_Symbol),],
  meta.m3[match(syms12[i],meta.mat3$Hugo_Symbol),],     
	main=syms12[i],	
	xlab="M2",ylab="M3",	
	pch=20)
## they are monotonously increasing relationships, so doesn't matter which samples to use.
```

## Load Clinical data
```{r}
meta.clinical <- read.table(file.path(metabric_dir,"data_clinical_patient.txt"),sep="\t",header=T)
table(meta.clinical$ER_IHC) ## 1817

if(0){
  meta.clinical2 <- read.table(file.path(metabric_dir,"data_clinical_sample.txt"),sep="\t",header=T)
  table(meta.clinical2$ER_STATUS) ## 1825 - not used this one
}

meta.clinical <- meta.clinical %>% left_join(meta.clinical2,by="PATIENT_ID")

meta.clinical$PATIENT_ID <- gsub("-",".",meta.clinical$PATIENT_ID)

##
used.ids <- colnames(meta.m3)
table(used.ids %in% meta.clinical$PATIENT_ID) ## all samples' records exist in clinical metadata

meta.clinical <- meta.clinical %>% filter(PATIENT_ID %in% used.ids)

```

```{r}
meta.clin.1 <- meta.clinical %>%
	filter(ER_STATUS %in% c("Positive","Negative")) %>%
	filter(PR_STATUS %in% c("Positive","Negative")) %>%
	filter(HER2_STATUS %in% c("Positive","Negative"))
##
limma::vennDiagram(cbind(
	`ER+`=(meta.clinical$ER_STATUS=="Positive"),
	`PR+`=(meta.clinical$PR_STATUS=="Positive"),
	`HER2+`=(meta.clinical$HER2_STATUS=="Positive")),
main="METABRIC samples")
```

## Patient IDs per category
```{r}
meta.er.pos.ids <- (meta.clinical %>% 
	filter(
		(ER_STATUS == "Positive" | 
		PR_STATUS == "Positive")
			& HER2_STATUS == "Negative"))$PATIENT_ID # 445

meta.her2.pos.ids <- (meta.clinical %>% 
	filter(ER_STATUS == "Negative" & 
		PR_STATUS == "Negative" &
		HER2_STATUS == "Positive"))$PATIENT_ID # 37

meta.dp.ids <- (meta.clinical %>% 
	filter((ER_STATUS == "Positive" | 
		PR_STATUS == "Positive")
			& HER2_STATUS == "Positive"))$PATIENT_ID # 126

meta.tnbc.ids <- (meta.clinical %>% 
	filter(ER_STATUS == "Negative" & 
		PR_STATUS == "Negative" &
		HER2_STATUS == "Negative"))$PATIENT_ID # 37

meta.all.ids <- meta.clinical$PATIENT_ID

meta.ids <- list(
	hr=meta.er.pos.ids,
	her2=meta.her2.pos.ids,
	dp=meta.dp.ids,
	tnbc=meta.tnbc.ids,
	all = meta.all.ids
)

sapply(meta.ids,length)
```

## Save data in rda
```{r}
setwd("~/Dropbox (HMS)/_BTIL_/projects/hr_apm_paper/data/RData")
save(meta.ids,meta.clinical,meta.syms,meta.m1,meta.m3,file=file.path(obj_dir,"metabric_subset.rda"))
```